twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@TetranzSelect2Entity/Form/fields.html.twig'

    globals:
        anniversary: '@app.anniversaries'
        recruitment: '@app.new_recruits'

when@test:
    twig:
        strict_variables: true